import type { Metadata } from "next";
import "../shared/ui/globals.css";
import { AppProviders } from "@/shared/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" suppressHydrationWarning>
      <body>
        <AppProviders>{children}</AppProviders>
        <script
          dangerouslySetInnerHTML={{
            __html:
              "(function(){try{var k='theme',m=localStorage.getItem(k);var s=window.matchMedia('(prefers-color-scheme: dark)').matches;var d=document.documentElement;d.classList.toggle('dark',m?m==='dark':s);}catch(e){}})();",
          }}
        />
      </body>
    </html>
  );
}
