import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../shared/ui/globals.css";
import { AppProviders } from "@/shared/providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppProviders>{children}</AppProviders>
        <script
          dangerouslySetInnerHTML={{
            __html:
              "(function(){try{var k='theme',m=localStorage.getItem(k);var s=window.matchMedia('(prefers-color-scheme: dark)').matches;var d=document.documentElement;d.classList.toggle('dark',m?m==='dark':s);}catch(e){}})();",
          }}
        />
      </body>
    </html>
  );
}
